# Generated by Django 2.0.5 on 2019-02-15 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_output', '0002_auto_20180909_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenticationinfo',
            options={'verbose_name': 'Authentication Info', 'verbose_name_plural': 'Authentication Info'},
        ),
        migrations.AlterModelOptions(
            name='endpoint',
            options={'verbose_name': 'End Point', 'verbose_name_plural': 'End Points'},
        ),
    ]
